### PR TITLE
WIP - buggy Julia 0.4 support

### PR DESCRIPTION
**Pull request by benmoran**
I've been trying to make the modifications discussed in issue #38.  It's not there yet - don't merge it!

I can eval quite a few Julia commands, but still get errors and segfaults (running on Ubuntu 14.04, system Python 2.7.6 and Julia 0.4.1 from julia-releases).

The main issue I'm fighting at the moment is that ``import julia; j = julia.Julia()`` gives:

    InitError(:PyCall,PyError (:PyCapsule_Import) <type 'exceptions.ImportError'>
    ImportError('PyCapsule_Import could not import module "datetime.datetime_CAPI"',)

It looks similar to the bug reported here but not resolved: https://github.com/stevengj/PyCall.jl/issues/178

Rebuilding PyCall doesn't seem to help.

I wonder if it is because the datetime module has already been initialized?

### CODE REVIEW

**Comment by stevengj** [comment]
@benmoran, thanks for working on this.  Do you get that error from `using PyCall` in Julia?

**Comment by benmoran** [comment]
No, it's fine if I use PyCall in Julia. In fact I can run Julia, use PyCall, @pyimport julia and then observe the error in the same Julia process where it had previously worked.

**Comment by stevengj** [comment]
What happens if you do:
```jl
using PyCall
import PyCall: @pycheckn, @pysym, PyDateTime_CAPI
unsafe_load(@pycheckn ccall((@pysym :PyCapsule_Import),
                                            Ptr{PyDateTime_CAPI}, (Ptr{UInt8}, Cint),
                                            "datetime.datetime_CAPI", 0))
```
in Julia?  Calling this multiple times works for me, so I don't think it's a problem with it already being loaded.

**Comment by sebastroy** [comment]
I have been working on this sporadically as well. I use python 3.5 though and I get different errors. In my case I can't manage to get the 

         res = self.api.jl_call2(void_p(self.api.convert), void_p(self.api.PyObject),void_p(ans))

working. I tried a handful of variation on the "self.api.convert" generation but they all generate a segfault when the one quoted above is invoked. If I skip the "base" part I can get it working partially. Partially in the sense that I can get julia to execute commands appropriately but I can't get the results back as a python object.

**Comment by benmoran** [comment]
@stevengj Calling unsafe_load ... as above works fine in Julia for me as well.

**Comment by sebastroy** [comment]
Allright I got it I think! I can build without errors, import julia and declare a j = julia.Julia() without error. I will see if I can make it really work and submit a patch. Way less radical changes than this pull request BTW. But then again I haven't studied the above changes. My gut feeling is that it's not necessary to make so many changes but maybe I'm missing something. Also, not sure about python 2 vs 3 compatiblity...

**Comment by benmoran** [comment]
@sebastroy you're right, this pull request also has other changes to try to make Julia stack traces better visible - I was finding this helpful for debugging.

**Comment by benmoran** [comment]
There are two things going on outside PyJulia - the Julia version and PyCall version.  I have a working setup of older code, and a new one.
 
 - working: (Julia 0.3, pyjulia master, PyCall 32b10a5...)  
 - not working: (Julia 0.4.1, benmoran/pyjulia julia-0.4, PyCall master) 

The second one gives the ``PyCapsule_Import could not import module "datetime.datetime_CAPI"`` error on ``Julia.call("using PyCall")``.

This might be due to changes in PyCall rather than just the Julia version number.  (I can't check them separately because I can't run the new PyCall with Julia 0.3 or vice versa, due to dependencies being incompatible.)

The main change in the new PyCall is that the ``PyCall.pyinitalize()`` function has gone away.  I removed the call entirely in the pyjulia branch here - as far as I could tell it's no longer necessary.  But if I try to ``api.call("@pyimport datetime")`` in my working Julia 0.3 setup after ``using PyCall`` but before ``pyinitialize(C_NULL)`` then it gives me the same error from PyCapsule_Import.  (In the Julia 0.3 shell itself ``using PyCall; @pyimport datetime`` works fine.)

So @stevengj - am I missing some necessary initialization step for the new version of PyCall?

(Also, as far as I can tell, the ImportError results not because the datetime .so file fails to dlload correctly, but because "datetime" doesn't appear in sys.modules afterwards).

**Comment by benmoran** [comment]
Superceded by https://github.com/JuliaLang/pyjulia/pull/47

**Pull request closed without merging**
